# Copyright 2021 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

name: site
on:
  push:
    branches:
      - master
    paths:
      - site/**
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Xskipper repository
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
      - name: Install Material for MkDocs
        run: |
          pip install mkdocs-material
          pip install mkdocs-redirects
          pip install mkdocs-markdownextradata-plugin
          pip install mike
      - name: Deploying Site
        working-directory: ./site
        run: |
          export SITE_VERSION=`sed -n 's/version in ThisBuild := "\(.*\)"/\1/p' version.sbt`
          echo "SITE_VERSION=$SITE_VERSION" >> $GITHUB_ENV
          git config --global user.email "xskipperci@gmail.com"
          git config --global user.name "Xskipper CI"
          git fetch origin xskipper-site
          mike deploy --push --remote origin --branch xskipper-site master